### ISSUE TITLE
Transaction already in progress

### ISSUE THREAD

**Issue by Oclair** [AnotherKamila/tarsnap-periodic#3]
Hi there,
Does only performing one type daily/weekly/monthly backups make sense?

or is there some other issue at play here?

Is there a facility to offset the periodic calls for the scripts?

Thanks for your assistance!
Oclair

> -- BEGIN Edited monthly run output --
> Doing tarsnap monthly backups:
>   * making backup: ROOT-monthly-2017-04
> tarsnap: Transaction already in progress
> tarsnap: Error creating new archive
> tarsnap: Error exit delayed from previous errors.
> 
> -- End of monthly output --

**Comment by AnotherKamila** [comment]
Hi,

sorry for the late reply, GitHub or something on the way ate the email, so I wasn't notified.

Performing only the type you need totally makes sense; on the production system that I wrote this for we only do weekly and monthly backups.

As for the offsetting / setting the time for the execution, that is governed by periodic, as this is executed together with (actually by) the rest of the `periodic` system. Therefore you would have to shift the execution of that whole thing; you can do that by editing the system crontab as mentioned in `man periodic`.

**Comment by AnotherKamila** [comment]
And the "Transaction already in progress" error was apparently caused because something else (maybe a previous execution of this?) was executing `tarsnap` at the same time.

The first tarsnap backup can take a very long time if you are backing up a lot. Therefore I suggest running it by hand and letting it finish before turning on these scripts. Further backups will be incremental, so they shouldn't take that long. (Aside: if you are indeed backing up so much data that this is taking a long time, you might want to check that you are not backing up things you don't need, as having a lot of data might eat tarsnap credit rather quickly!)

**Comment by AnotherKamila** [comment]
Closing this, as I mentioned this in the README.
